#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UnviredMonoDroidSample.Resource", IsApplication=true)]

namespace UnviredMonoDroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::UnviredMonoDroidKernel.Resource.Array.domains = global::UnviredMonoDroidSample.Resource.Array.domains;
			global::UnviredMonoDroidKernel.Resource.Drawable.logo = global::UnviredMonoDroidSample.Resource.Drawable.logo;
			global::UnviredMonoDroidKernel.Resource.Drawable.Microsoft = global::UnviredMonoDroidSample.Resource.Drawable.Microsoft;
			global::UnviredMonoDroidKernel.Resource.Drawable.unvired = global::UnviredMonoDroidSample.Resource.Drawable.unvired;
			global::UnviredMonoDroidKernel.Resource.Id.CancelButton = global::UnviredMonoDroidSample.Resource.Id.CancelButton;
			global::UnviredMonoDroidKernel.Resource.Id.CompanyLabel = global::UnviredMonoDroidSample.Resource.Id.CompanyLabel;
			global::UnviredMonoDroidKernel.Resource.Id.CompanyTextField = global::UnviredMonoDroidSample.Resource.Id.CompanyTextField;
			global::UnviredMonoDroidKernel.Resource.Id.DomainLabel = global::UnviredMonoDroidSample.Resource.Id.DomainLabel;
			global::UnviredMonoDroidKernel.Resource.Id.DomainTextField = global::UnviredMonoDroidSample.Resource.Id.DomainTextField;
			global::UnviredMonoDroidKernel.Resource.Id.FinalURLLabel = global::UnviredMonoDroidSample.Resource.Id.FinalURLLabel;
			global::UnviredMonoDroidKernel.Resource.Id.HeadingLabel = global::UnviredMonoDroidSample.Resource.Id.HeadingLabel;
			global::UnviredMonoDroidKernel.Resource.Id.LoginButton = global::UnviredMonoDroidSample.Resource.Id.LoginButton;
			global::UnviredMonoDroidKernel.Resource.Id.LoginTypeImage = global::UnviredMonoDroidSample.Resource.Id.LoginTypeImage;
			global::UnviredMonoDroidKernel.Resource.Id.OptionsButton = global::UnviredMonoDroidSample.Resource.Id.OptionsButton;
			global::UnviredMonoDroidKernel.Resource.Id.PasswordTextfield = global::UnviredMonoDroidSample.Resource.Id.PasswordTextfield;
			global::UnviredMonoDroidKernel.Resource.Id.URLLabel = global::UnviredMonoDroidSample.Resource.Id.URLLabel;
			global::UnviredMonoDroidKernel.Resource.Id.URLPrefixLabel = global::UnviredMonoDroidSample.Resource.Id.URLPrefixLabel;
			global::UnviredMonoDroidKernel.Resource.Id.URLPrefixSpinner = global::UnviredMonoDroidSample.Resource.Id.URLPrefixSpinner;
			global::UnviredMonoDroidKernel.Resource.Id.URLTextfield = global::UnviredMonoDroidSample.Resource.Id.URLTextfield;
			global::UnviredMonoDroidKernel.Resource.Id.UserNameTextField = global::UnviredMonoDroidSample.Resource.Id.UserNameTextField;
			global::UnviredMonoDroidKernel.Resource.Id.linearLayout1 = global::UnviredMonoDroidSample.Resource.Id.linearLayout1;
			global::UnviredMonoDroidKernel.Resource.Id.linearLayout2 = global::UnviredMonoDroidSample.Resource.Id.linearLayout2;
			global::UnviredMonoDroidKernel.Resource.Id.scroll = global::UnviredMonoDroidSample.Resource.Id.scroll;
			global::UnviredMonoDroidKernel.Resource.Id.textView5 = global::UnviredMonoDroidSample.Resource.Id.textView5;
			global::UnviredMonoDroidKernel.Resource.Id.textView6 = global::UnviredMonoDroidSample.Resource.Id.textView6;
			global::UnviredMonoDroidKernel.Resource.Layout.LoginPage = global::UnviredMonoDroidSample.Resource.Layout.LoginPage;
			global::UnviredMonoDroidKernel.Resource.String.DomainSpinner = global::UnviredMonoDroidSample.Resource.String.DomainSpinner;
			global::UnviredMonoDroidKernel.Resource.String.library_name = global::UnviredMonoDroidSample.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int domains = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Microsoft = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splashimage = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int unvired = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int CancelButton = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int CompanyLabel = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int CompanyTextField = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int DomainLabel = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int DomainTextField = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int FinalURLLabel = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int HeadingLabel = 2131165188;
			
			// aapt resource value: 0x7f070013
			public const int LoginButton = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int LoginTypeImage = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int OptionsButton = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int PasswordTextfield = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int URLLabel = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int URLPrefixLabel = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int URLPrefixSpinner = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int URLTextfield = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int UserNameTextField = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout2 = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int scroll = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int textView5 = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int textView6 = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HelloWorldScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginPage = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int DomainSpinner = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int library_name = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
